version: '3.5'
services:
  dify2openai:
    container_name: dify2openai
    image: dify2openai:latest
    network_mode: bridge
    ports:
      - "5040:5040"
    restart: always
    volumes:
      - /home/wizard/data/dify2openai:/usr/src/app/data
    environment: 
      - DIFY_API_URL=http://192.168.3.56:5039/v1
      - BOT_TYPE=Chat
      - PORT=5040