version: '3.5'
services:
  dify2openai:
    container_name: dify2openai
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: bridge
    ports:
      - "5040:5040"
    restart: always
    environment: 
      - DIFY_API_URL=http://192.168.3.80/v1
      - PORT=5040